[wokwi]
version = 1
elf      = "build/esp32.esp32.esp32doit-devkit-v1/PetPulse-Iot.ino.elf"
firmware = "build/esp32.esp32.esp32doit-devkit-v1/PetPulse-Iot.ino.bin"

[[net.forward]]
from = "0.0.0.0:8280"
to   = "target:80"